WEBUMENIA-1340, WEBUMENIA-1341: link item to authorities + roles
SlovakNationalGallery/webumenia.sk pull request #351
Opened 2020-09-17 07:56 UTC by martin-havala

# Description

- admin/item: author is now using selectize; so user can quickly add items from authorities / new strings, therefore old-fashioned behaviour is still posible
- admin/item: item_authorities - small vue component, where user can add author + predefined role, so far we're keeping old model for storing of pivot table (next step - index table for roles and using index_id instead of role as a value)

I guess I'll create small repo for vue components, as now we're having vue-colors and vue-linked-combos

Fixes # (link to Jira or GitHub issue)
[WEBUMENIA-1340](https://jira.sng.sk/browse/WEBUMENIA-1340)
[WEBUMENIA-1341](https://jira.sng.sk/browse/WEBUMENIA-1341)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2020-10-15 08:23 UTC, eronisko requested changes
I think the role values belong to config files -- please see my comments below.

2020-10-15 08:23 UTC, eronisko commented on app/Forms/Types/ItemAuthoritiesType.php
> +        $view->vars['authorities_choices'] = \App\Authority::orderBy('name', 'asc')->get(['id as key', 'name as value'])->toJson();
is `toJson()` necessary?

2020-10-15 08:23 UTC, eronisko commented on database/migrations/2020_09_10_120620_create_authority_roles_table.php
> +            ["author.atelier",               "ateliér",                         "atelier"],
The fact that you've managed to name all roles inside a migration tells me that this is probably not a good candidate for storing inside a DB. 

I would store this data in the database if we were to curate this list dynamically. Then I would also expect that we'd have a UI for managing this list (including the translations).

As for something that is not likely to change very often, I would much prefer to keep this in config files. It's easier to manage and we get the added benefit of tracking changes.

* The list of roles could go in `/config/authority_roles.php`
* The translations can go to `/resources/lang/en/authority_roles.php` etc

The value would then be kept as a single column inside `authority_item` table (I think)

2020-10-15 08:23 UTC, eronisko commented on public/css/vue/vue-linked-combos.css
> +.linked-combos {
Is there a way for us to distinguish 3rd-party (vendor) and our CSS? Is there also a way to plug it inside our Mix (Less) pipeline?

2020-10-15 10:32 UTC, martin-havala commented on tests/BrowserKit/AdminItemFormTest.php
> -            ->type('Test Author', 'item[author]')
I was not able to fix it in a meaningful amount of time, opened to suggestions
problem: I've used ChoiceType + .selectizr for input, so maybe I need to populate options first and then pick one of them, but I did not succeed here either

2020-10-15 10:33 UTC, martin-havala commented on database/migrations/2020_09_10_120620_create_authority_roles_table.php
> +            ["author.atelier",               "ateliér",                         "atelier"],
2nd iteration should be to have a normal translation table, and then also czech language could be handled

2020-10-15 10:38 UTC, martin-havala commented on public/css/vue/vue-linked-combos.css
> +.linked-combos {
I suggested to @igor-kamil to have a small repo for our vue components... for now we have vue-color [slider + color slider] and this one(linked-combos), which uses https://www.npmjs.com/package/vue-select

2020-10-29 13:43 UTC, eronisko commented on public/css/vue/vue-linked-combos.css
> +.linked-combos {
OK, let's leave it for now then

2020-10-29 13:44 UTC, eronisko commented on database/migrations/2020_09_10_120620_create_authority_roles_table.php
> +            ["author.atelier",               "ateliér",                         "atelier"],
I still think this is stable enough to live in a config file. @igor-kamil @rastislav-chynoransky ?

2020-10-29 13:51 UTC, eronisko commented on tests/BrowserKit/AdminItemFormTest.php
> -            ->type('Test Author', 'item[author]')
What kind of error did you get?

2020-11-04 13:30 UTC, martin-havala commented on app/Forms/Types/ItemAuthoritiesType.php
> +        $view->vars['authorities_choices'] = \App\Authority::orderBy('name', 'asc')->get(['id as key', 'name as value'])->toJson();
no ;)

2020-11-04 13:36 UTC, martin-havala commented on tests/BrowserKit/AdminItemFormTest.php
> -            ->type('Test Author', 'item[author]')
first it was problem with selector, which is _item[author]]_ now, then should I populate values and pick some, because it's empty now

2020-11-11 13:44 UTC, martin-havala commented on database/migrations/2020_09_10_120620_create_authority_roles_table.php
> +            ["author.atelier",               "ateliér",                         "atelier"],
@igor-kamil, @rastislav-chynoransky ?

2020-11-11 13:45 UTC, martin-havala commented on database/migrations/2020_09_10_120620_create_authority_roles_table.php
> +            ["author.atelier",               "ateliér",                         "atelier"],
if so, we should rather create a translated index within database

2020-12-10 14:12 UTC, eronisko approved these changes
Nice job, thanks for working in my suggestions!

I think you've left in a couple of model classes but apart from that this is good to go.

2020-12-11 11:10 UTC, merged