[import] Add PNP trienale importer
SlovakNationalGallery/webumenia.sk pull request #352
Opened 2020-09-29 19:03 UTC by rastislav-chynoransky

Fixes https://jira.sng.sk/projects/PNP/issues/PNP-4

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2020-09-29 19:09 UTC, rastislav-chynoransky commented on app/Importers/PnpTrienaleImporter.php
> +        ],
@mcudrnak please check these translations

2020-10-15 10:13 UTC, eronisko requested changes
Looks good overall, just one thing: I don't think `$useTranslationFallback` is doing anything.

2020-10-15 10:13 UTC, eronisko commented on app/Item.php
> +    protected $useTranslationFallback;
Is this actually doing anything?

2020-10-15 10:48 UTC, eronisko requested changes

2020-10-15 10:48 UTC, eronisko commented on app/Importers/PnpTrienaleImporter.php
> +    }
Actually, now that I've thought about this, why not add two additonal columns instead? We don't have a native JSON support in the current DB version, so I'd hold off with using JSON like this. 

This way we're losing many of the Eloquent features and we can't really use or update these fields very easily.

I'll happily be persuaded otherwise, but right now, I have a strong preference for using plain-old columns for this. cc @igor-kamil

2020-10-15 11:04 UTC, rastislav-chynoransky commented on app/Item.php
> +    protected $useTranslationFallback;
It's unexisting otherwise

2020-10-15 11:17 UTC, rastislav-chynoransky commented on app/Importers/PnpTrienaleImporter.php
> +    }
This is the most universal thing we'd come up with. We try to design the structure for future custom data that we don't use (award and award category will be displayed only at PNP website).

2020-10-15 11:35 UTC, eronisko commented on app/Item.php
> +    protected $useTranslationFallback;
But does its existence make any difference? I don't see it being used anywhere.

2020-10-15 11:47 UTC, rastislav-chynoransky commented on app/Item.php
> +    protected $useTranslationFallback;
Ah, sure... https://github.com/Astrotomic/laravel-translatable/blob/master/src/Translatable/Translatable.php#L445

2020-10-15 11:53 UTC, rastislav-chynoransky commented on app/Item.php
> +    protected $useTranslationFallback;
We want to set it `false` so it wouldn't fallback to SK language

2020-10-15 12:05 UTC, eronisko commented on app/Item.php
> +    protected $useTranslationFallback;
Ah, my bad! Sorry and thanks.

2020-10-15 12:21 UTC, eronisko commented on app/Importers/PnpTrienaleImporter.php
> +    }
My 2c: it is a good approach when there's a native support for it in the DB and application. Right now, it isn't really much different from saving them as `?award=abc&award_category=xyz` or any other arbitrary format. You have to parse them every time you want to use them and any effort for change (e.g. "migration") would be a search & replace exercise.

I totally get the need and I think this is another good reason to move to MySQL 5.7. Moving these sparse columns to a JSON column shouldn't be too much hassle after that.

2020-10-26 19:52 UTC, igor-kamil requested changes
since "Inventární číslo" column is missing in the current XLS file, it ends up with `Undefined index`
please add auto-generating of ID/identifier

2020-10-26 20:14 UTC, igor-kamil approved these changes
sorry my fail. it works nicely. ready to go!

2020-10-26 20:47 UTC, merged