Feature/webumenia 1440
SlovakNationalGallery/webumenia.sk pull request #354
Opened 2020-10-01 15:20 UTC by martin-havala

# Description

carousel / hero image style upgrade
 - unified handling of the background image
 - used img + src + srcset for responsive behaviour
 - resurrected slide detail
 - removed flickity - replaced by slick(which was already used at the artwork->detail page)

Fixes [WEBUMENIA-1440](https://jira.sng.sk/browse/WEBUMENIA-1440)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2020-10-08 07:37 UTC, eronisko commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
I'd use a `HasHeaderImage` Trait instead of extending `Model` (composition over inheritance)

2020-10-08 14:25 UTC, martin-havala commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
and what to do with constants then?

2020-10-10 08:26 UTC, eronisko commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
Good point. Maybe use static functions for that?

2020-10-11 10:25 UTC, martin-havala commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
or stick to good old inheritance? we 're inheriting from little class targeting one small problem... or we could have a helper functions where you have to provide all variables as call parameters, but that's rather clumsy

2020-10-11 10:36 UTC, rastislav-chynoransky commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
Or could those be trait properties?

2020-10-11 11:11 UTC, martin-havala commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
You cannot override trait properties in the same class, just in extending class, right?

2020-10-11 19:43 UTC, eronisko commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
@martin-havala is overriding something like `getImageProperty()` not an option?

2020-10-15 06:55 UTC, martin-havala commented on app/HeaderImageModel.php
> +class HeaderImageModel extends Model{
done, I just see no reason to use a function where simple variable has to be enough

2020-10-15 12:58 UTC, eronisko requested changes
Almost there! Loving all that deleted code 🏆.

2020-10-15 12:58 UTC, eronisko commented on app/Article.php
> +    use HasHeaderImageTrait;
I think you're missing an import at the top

2020-10-15 12:58 UTC, eronisko commented on app/Article.php
> +        $preview_path = preg_replace("/(\.[0-9a-z]+$)/i", ".thumbnail" . "$1", $path);
Would this work?
```suggestion
        $preview_path = Str::replaceLast('.', '.thumbnail.', $path);
```

2020-10-15 12:58 UTC, eronisko commented on app/Article.php
>      public function getThumbnailImage($full = false)
I think this belongs inside the `HasHeaderImageTrait` now

2020-10-15 12:58 UTC, eronisko commented on app/Collection.php
> +        return Carbon::parse($value)->format('d. m. Y'); //Change the format to whichever you desire
I'd use https://laravel.com/docs/5.7/eloquent-mutators#date-mutators and then format the date in view. If you want to get super-fancy, this is also an option for keeping the formatting consistent:

https://laravel.com/docs/5.7/blade#extending-blade

2020-10-15 12:58 UTC, eronisko commented on app/Collection.php
> +        return getEstimateReadingTime($this->text, App::getLocale() );
How does this work? I can't see `getEstimateReadingTime` defined anywhere

2020-10-15 12:58 UTC, eronisko commented on database/migrations/2020_10_01_112350_update_collections_main_images.php
> +		  DB::statement('UPDATE `slides` SET `image` =  CONCAT(id,"/",image)');
Do we really need to do this? Genuine question. Seems like this could be handled at app level, but I might be missing something.

2020-10-15 12:58 UTC, eronisko commented on app/Http/Controllers/ArticleController.php
> +        $article->main_image = $article->uploadHeaderImage($main_image);
🔥

2020-10-15 12:58 UTC, eronisko commented on app/HasHeaderImageTrait.php
> +<?php
Usually, this would go into `app/Traits/HasHeaderImage.php`

2020-10-15 12:58 UTC, eronisko commented on resources/views/collections/form.blade.php
> +					 onerror="this.onerror=null;this.srcset=''"/>
Identation seems off

2020-10-15 12:58 UTC, eronisko commented on resources/views/intro.blade.php
> +    // lazyLoad: 'progressive',
```suggestion
```

2020-10-15 12:58 UTC, eronisko commented on resources/views/intro.blade.php
> +    slidesToShow: 1,
Identation

2020-10-15 12:58 UTC, eronisko commented on resources/views/kolekcia.blade.php
> +                {!! $collection->published_date !!}
Indentation

2020-10-15 12:58 UTC, eronisko commented on resources/views/layouts/master.blade.php
> +    {!! Html::script('js/jquery.easing.min.js') !!}
Indentation (not just yours 🙄)

2020-10-15 12:58 UTC, eronisko commented on resources/less/custom.less
> +    height:100%;
```suggestion
  img {
    position: absolute;
    width: 100%;
    height: 100%;
```

2020-10-15 12:58 UTC, eronisko commented on resources/less/custom.less
> +  .slick-active button{
```suggestion
.slick-pagination .slick-dots {
  position: relative;
  bottom: unset;
  text-align: right;
  padding-top: .5rem;

  li button {
    font-size: 1rem;
    color: @gray-dark;
    opacity: 0.7;
    &:before {
      content: '';
    }
  }
  .slick-active button {
```

2020-10-15 12:58 UTC, eronisko commented on resources/less/custom.less
> +  {
```suggestion
  .slick-prev, .slick-next {
```

2020-10-15 12:58 UTC, eronisko commented on app/HasHeaderImageTrait.php
> +            return ($full ? public_path() : '') . $this->artworks_dir . $this->id . '.jpg'; // fallback for old collections
Do you know what these comment mean? If not I'd nuke them all. Maybe @igor-kamil would know what they mean?

2020-10-15 12:59 UTC, eronisko commented on app/HasHeaderImageTrait.php
> +<?php
Then you don't need the word `Trait` in the class name.

2020-10-28 08:56 UTC, martin-havala commented on app/Article.php
> +    use HasHeaderImageTrait;
no, it's in the same namespace

2020-10-28 09:08 UTC, martin-havala commented on app/Collection.php
> +        return getEstimateReadingTime($this->text, App::getLocale() );
it's under app/Helpers/general.php

2020-10-29 13:42 UTC, eronisko requested changes
Thanks for all the fixes. Most of my suggestions are very minor except this one: can you please move `App\HasHeaderImageTrait`  to `App\Traits\HasHeaderImage`? I know it seems silly, but it is the standard for Laravel apps and I suspect it's causing some lookup/import issues right now.

2020-10-29 13:42 UTC, eronisko commented on app/Article.php
> +use Illuminate\Support\Facades\App;
It's strange that this is required. I'd expect something like `use App\Traits\HasHeaderImage;` though :)

2020-10-29 13:42 UTC, eronisko commented on app/Collection.php
> +        return getEstimateReadingTime($this->text, App::getLocale() );
Ah, got it, thanks.

2020-10-29 13:42 UTC, eronisko commented on app/Helpers/general.php
> +function getEstimateReadingTime($content, $locale, $wpm = 200) {
Is this a typo? (if not, feel free to ignore)
```suggestion
function getEstimatedReadingTime($content, $locale, $wpm = 200) {
```

2020-10-29 13:42 UTC, eronisko commented on app/Helpers/general.php
> +function getEstimateReadingTime($content, $locale, $wpm = 200) {
BTW, do we need `$locale` and `$wpm` here?

`$locale` does not seem to be used & `$wpm` could probably be a constant.

2020-10-29 13:42 UTC, eronisko commented on app/Providers/AppServiceProvider.php
> +        Blade::directive('date', function ($expression) {
Nice!

2020-10-29 13:42 UTC, eronisko commented on resources/views/frontend/collection/index.blade.php
> +                    @date($collection->created_at) &nbsp;&middot;&nbsp;
👌

2020-10-29 13:48 UTC, rastislav-chynoransky commented on app/Helpers/general.php
> +function getEstimateReadingTime($content, $locale, $wpm = 200) {
I'd say that @martin-havala meant to pass `$locale` to `trans_choice`

2020-10-29 13:51 UTC, rastislav-chynoransky commented
> Thanks for all the fixes. Most of my suggestions are very minor except this one: can you please move `App\HasHeaderImageTrait` to `App\Traits\HasHeaderImage`? I know it seems silly, but it is the standard for Laravel apps and I suspect it's causing some lookup/import issues right now.

Laravel's convention is using `Concern`s for traits and `Contract`s for interfaces -- we already got these namespaces in `App`.

2020-10-29 14:11 UTC, eronisko commented
> Laravel's convention is using `Concerns` for traits and `Contracts` for interfaces

Hah! I stand corrected. I've seen `app/Traits/ this [at Spatie](https://github.com/spatie/laravel-activitylog/tree/master/src) and we used it for Register architektury, but @rastislav-chynoransky is right, the Laravel team is using a different convention. 

I'd be up for moving this to `Concerns`.

2020-10-29 14:13 UTC, eronisko commented on app/Helpers/general.php
> +function getEstimateReadingTime($content, $locale, $wpm = 200) {
And would that be even necessary? Doesn't `trans_choice()` use the current app locale by default?

2020-10-29 14:19 UTC, rastislav-chynoransky commented on app/Helpers/general.php
> +function getEstimateReadingTime($content, $locale, $wpm = 200) {
It can be optional (`=== null`). Just to keep it universal if we want to use it somewhere else e.g. when sending e-mails or where the locale is not set globally since it's a general helper.

2020-10-30 08:25 UTC, martin-havala commented on app/HasHeaderImageTrait.php
> +            return ($full ? public_path() : '') . $this->artworks_dir . $this->id . '.jpg'; // fallback for old collections
full_path is actual path on drive, so you need it e.g. for resizing, while other one is just relative to main 
but I've cleaned it up a bit ;)

2020-10-30 08:26 UTC, martin-havala commented on app/Article.php
> +use Illuminate\Support\Facades\App;
may I leave HasHeaderImageTrait ? It seem that most of providers/Repositories etc keep their suffix

2020-10-30 08:33 UTC, eronisko commented on app/Article.php
> +use Illuminate\Support\Facades\App;
Cool, makes sense

2020-10-30 09:56 UTC, eronisko commented on app/Article.php
> +use Illuminate\Support\Facades\App;
Is `use Illuminate\Support\Facades\App;` still required?

2020-11-04 07:22 UTC, martin-havala commented
> Thanks for all the fixes. Most of my suggestions are very minor except this one: can you please move `App\HasHeaderImageTrait` to `App\Traits\HasHeaderImage`? I know it seems silly, but it is the standard for Laravel apps and I suspect it's causing some lookup/import issues right now.

2020-11-11 12:36 UTC, mcudrnak commented
@eronisko @igor-kamil please review and close asap.

2020-11-11 13:26 UTC, eronisko commented
Please resolve conflicts and I'll take one last look. In general, this is good imho.

2020-11-11 13:46 UTC, eronisko approved these changes
🚀

2020-11-19 07:37 UTC, eronisko commented
@martin-havala could we please make a new branch (e.g. `redesign`) and merge this into it?

2020-11-20 10:51 UTC, eronisko requested changes
Some merging issues, but looking good otherwise :)

2020-11-20 10:51 UTC, eronisko commented on webpack.mix.js
> +    // // CSS
```suggestion
    // CSS
```

2020-11-20 10:51 UTC, eronisko commented on resources/js/app.js
> +require( 'slick-carousel');
I think this can safely go at the top after `bootstrap` (it's not a component)

2020-11-20 10:51 UTC, eronisko commented on public/main.js
> +(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["main"],{
This seems like a generated file that shouldn't be checked into git.

2020-11-20 10:51 UTC, eronisko commented on resources/views/layouts/master.blade.php
> +		<meta name="author" content="lab.SNG">
Can you please double-check this file? Looks like there's some duplication here.

2020-11-20 12:56 UTC, martin-havala commented on resources/views/layouts/master.blade.php
> +    <meta charset="utf-8">
here it has to be just indentation (4 spaces)

2020-11-25 07:37 UTC, closed without merging