[harvest] fix harvest failed job
SlovakNationalGallery/webumenia.sk pull request #355
Opened 2020-10-04 19:28 UTC by rastislav-chynoransky

Fixes https://jira.sng.sk/browse/WEBUMENIA-1353

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2020-10-08 09:13 UTC, eronisko requested changes
Disclaimer: I haven't wrapped my head around the Harvester > Harvest/Importer > Record architecture yet. (Unfortuntely I'm quite confused by it)

So here are some general thoughts, happy to discuss them further

2020-10-08 09:13 UTC, eronisko commented on app/Harvest/Harvesters/AbstractHarvester.php
> +            $harvest->status_messages = trans('harvest.status_messages.finished', [
From here, I can't tell the difference between  `harvest.status_messages.finished` and `harvest.status_messages.completed`. Is there any other name (names) we could use?

2020-10-08 09:41 UTC, rastislav-chynoransky commented on app/Harvest/Harvesters/AbstractHarvester.php
> +    public function tryHarvestFailed(SpiceHarvesterHarvest $harvest) {
Great suggestion! There is obvious repetition of code that we need to refactor. However I'm not sure if the model should handle reporting logic and thus got a dependency to sentry.

2020-10-08 10:28 UTC, rastislav-chynoransky commented on app/Harvest/Harvesters/AbstractHarvester.php
> +    public function tryHarvestFailed(SpiceHarvesterHarvest $harvest) {
But I'm thinking maybe throwing the exception to sentry doesn't belong here at all...

2020-10-08 10:29 UTC, eronisko commented on app/Harvest/Harvesters/AbstractHarvester.php
> +    public function tryHarvestFailed(SpiceHarvesterHarvest $harvest) {
Good point. Two ideas off of the top of my head:

1. Firing an Event when a harvest fails: https://laravel.com/docs/6.x/events#registering-events-and-listeners
1. Adding another callback, e.g.
```php
// app\SpiceHarvesterHarvest.php
public function process(Closure $onProcess, Closure $onError) {
```

2020-10-08 12:49 UTC, rastislav-chynoransky commented
@eronisko I'm going to write more tests for harvester and will split this issue to `fix` and `feature` as those two are independent.

2020-10-09 07:49 UTC, eronisko approved these changes

2020-10-09 08:11 UTC, merged