Feature/webumenia 1455 slick
SlovakNationalGallery/webumenia.sk pull request #387
Opened 2020-11-11 13:34 UTC by martin-havala

# Description

content carousel - usable anywhere within ckEditor

Fixes [WEBUMENIA-1455](https://jira.sng.sk/browse/WEBUMENIA-1455)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2020-11-18 22:20 UTC, igor-kamil requested changes
works nicely. thank you for this. 
there is just this tiny issue within the comment + fix the conflict. 
afterwards it's good to go.
maybe it's also good to point out for users (@ustengrav ), that for including images within slick component in ckeditor - it's necessary to remove the width/height (which is btw always filled). otherwise the images appear stretched in the frontend (or maybe just override it with css rules)

2020-11-18 22:20 UTC, igor-kamil commented on resources/views/layouts/master.blade.php
> +	{!! Html::script('js/slick.js') !!}
since you placed `slick.js` directly into master layout - it's now obsolete to call it again in `autor.blade.php`, `clanok.blade.php`, `artwork_carousel_js.blade.php` etc 
(just run find `slick.js` for all `*.blade.php` files - and remove it please)

2020-11-18 22:26 UTC, igor-kamil commented
also since there is https://github.com/SlovakNationalGallery/webumenia.sk/pull/382 already merged - I think the best approach will be to include slick.js within app.js ... what do you think @martin-havala ?

2020-11-19 13:07 UTC, closed without merging

2020-11-19 13:08 UTC, martin-havala commented
will be part of redesign story