WEBUMENIA-1543 Authority "sources" links
SlovakNationalGallery/webumenia.sk pull request #449
Opened 2021-02-12 14:06 UTC by eronisko

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [x] I have made corresponding changes to the documentation

2021-02-18 22:08 UTC, igor-kamil requested changes

2021-02-18 22:08 UTC, igor-kamil commented on database/migrations/2021_02_12_083807_add_type_to_links.php
> +            $table->string('type')->after('label')->nullable(false)->index();
to be honest - here I am just in doubts - whether not to set it to `->default('external')` ... 
but this is just a note. not a request. any reason?

2021-02-18 22:08 UTC, igor-kamil commented on resources/js/components/admin/LinksInput.vue
> +<template>
I like to see this component! 👍

2021-02-19 07:38 UTC, eronisko commented on database/migrations/2021_02_12_083807_add_type_to_links.php
> +            $table->string('type')->after('label')->nullable(false)->index();
A link without a `type` is not valid anymore. This way you have to be explicit about what type of link you're creating.

On DB side I prefer things to fail fast rather than silently accept incomplete input -- especially if the default is buried in a migration file.

2021-02-19 07:38 UTC, eronisko commented on app/Http/Controllers/AuthorityController.php
> +            ...collect($input['externalLinks'])->map(function($link) {
Great catch, thank you.

2021-02-19 07:39 UTC, eronisko commented on app/Http/Controllers/AuthorityController.php
> +        $input = convertEmptyStringsToNull(Input::all());
I thought that middleware was there but I wasn't sure wheter we ended up using it. I'll get rid of this and see what happens :)

2021-02-19 07:48 UTC, eronisko commented
@igor-kamil thanks for the thorough review! I've made the changes you requested.

2021-02-19 08:32 UTC, igor-kamil approved these changes
👌

2021-02-19 09:15 UTC, merged