Webumenia 1701 redirects
SlovakNationalGallery/webumenia.sk pull request #576
Opened 2021-11-22 22:30 UTC by igor-kamil

# Description

It uses https://github.com/spatie/laravel-missing-page-redirector 

<img width="1164" alt="Screenshot 2021-11-22 at 23 27 17" src="https://user-images.githubusercontent.com/2682941/142944595-4e244e05-8efa-458f-a205-42b9b70cb4d2.png">

Fixes WEBUMENIA-1701

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2021-11-23 07:00 UTC, eronisko requested changes
Nice, clean PR. There are some minor things here and there, but the reason why I'm not approving this (yet) is that I think when in comes to routing, we should be caching if we can -- please see the comments.

2021-11-23 13:27 UTC, igor-kamil commented on app/Listeners/ResolveRouteWasHit.php
> +        $redirect = Redirect::where('source_url', $event->missingUrl)->increment('counter');
I expected this question 😆 
I am better in SQL queries then digging the the data from GA... 
Also it's nicely visible in admin.

2021-11-23 13:48 UTC, igor-kamil commented on app/Http/Controllers/RedirectController.php
> +        $rules['source_url'] = $rules['source_url'] . ',source_url,' . $redirect->id;
good point. I added comment - for the future
I was facing with the problem of validation unique `source_url` on update - it was preventing from updating the given record.
https://stackoverflow.com/a/27194281/2660740
I admit this is not the most elegant solution...  but consistent with current implementation/pattern.

2021-11-23 21:58 UTC, mcudrnak commented on database/migrations/2021_11_22_194009_create_redirects_table.php
> +            $table->integer('counter')->default(0);
@eronisko i'm fine with the counter - though it can be viewed in GA too, it's a nice-to-have feature in the admin, not having to dig through GA when managing the redirects

2021-11-25 06:07 UTC, eronisko reviewed
Thanks for implementing the caching.

Please fix the remaining whitespace issue (tabs + spaces) and consider my new suggestions. I know the whitespace is a minor thing, but this is a brand new file and I think it deserves a good start for its journey :)

2021-11-25 06:07 UTC, eronisko commented on resources/views/redirects/form.blade.php
> +	@if (Session::has('message'))
FYI, this is still an issue.

2021-11-25 12:45 UTC, eronisko approved these changes

2021-11-25 12:51 UTC, igor-kamil commented on resources/views/redirects/form.blade.php
> +	@if (Session::has('message'))
(I have something broken in my SublimeText.
<img width="523" alt="Screenshot 2021-11-25 at 12 50 30" src="https://user-images.githubusercontent.com/2682941/143436735-002482dd-e440-4822-a1cf-25ab9e7070ba.png">
it should work automatically - apparently it stopped )

2021-11-25 12:53 UTC, eronisko commented on resources/views/redirects/form.blade.php
> +	@if (Session::has('message'))
Yeah... it's same for me on VS Code... It's probably being considerate if it cannot work out what's going on :D

2021-11-25 12:58 UTC, igor-kamil commented on app/Services/MissingPageRedirector/DatabaseRedirector.php
> +        return Cache::remember('redirects', 86400, function () {
I was also thinking about it... but I was unsure whether to keep it forever or rather not. 
Happy to commit this :)

2021-11-25 13:07 UTC, igor-kamil commented on app/Providers/EventServiceProvider.php
> +            ResolveRouteWasHit::class,
much better! thanx! 
naming is never-ending problem :P

2021-11-25 13:26 UTC, merged