add word-break:keep-all property globally
SlovakNationalGallery/webumenia.sk pull request #653
Opened 2022-03-15 16:25 UTC by rastislav-chynoransky

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes https://jira.sng.sk/browse/PNP-71

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2022-03-15 20:38 UTC, eronisko requested changes

2022-03-15 20:38 UTC, eronisko commented on resources/css/app-tailwind.css
> +        word-break: keep-all;
Please make a class for this on the `utilities` layer and then `@apply` it so that it can be used on `<body>` once we retire Bootstrap (Although I can see I didn't make a very good example here with the `.tailwind-rules.admin` class 😅)

Still, I'm kinda hesitant with making this global. I'd probably just make a utility class (even outside of Tailwind if it's easier) and apply it just where it matters, e.g. image thumbnails, descriptions, title. What does @igor-kamil think?

2022-03-15 20:40 UTC, eronisko commented on resources/css/app-tailwind.css
> +        word-break: keep-all;
Btw, these artworks are 😍

2022-03-15 21:50 UTC, rastislav-chynoransky commented on resources/css/app-tailwind.css
> +        word-break: keep-all;
Since this setting is the same as `normal` (default) and only affects CJK languages I'd prefer it to have set globally as there may be many places to apply it to (even in the future development).

2022-03-16 04:36 UTC, eronisko approved these changes

2022-03-16 06:40 UTC, merged