Feature/pnp 56 importer role
SlovakNationalGallery/webumenia.sk pull request #734
Opened 2022-08-16 13:04 UTC by rastislav-chynoransky

Fixes https://jira.sng.sk/browse/PNP-56

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2022-08-18 08:51 UTC, igor-kamil approved these changes
looks nice. 
this limits only one user with role "importer" for each import. but probably OK for now...

2022-08-18 09:00 UTC, eronisko requested changes
It's almost good to go, but the permission enforcement is a bit complex & I think it has a few holes -- I'd consider using Policies for this.

2022-08-18 09:07 UTC, rastislav-chynoransky commented on resources/views/imports/form.blade.php
> +			{!! Form::text('name', Request::old('name'), array('class' => 'form-control', 'placeholder' => '', 'disabled' => !$can_update)) !!}
It doesn't fit that well in the controller where the variable is set though...

2022-08-18 09:18 UTC, rastislav-chynoransky commented on routes/web.php
> -    Route::get('imports/launch/{id}', [ImportController::class, 'launch']);
If needed for a specific case there should be a way to assign multiple roles to a user.
Otherwise it doesn't make much sense for editors to have import permissions.

2022-08-18 09:19 UTC, rastislav-chynoransky commented on app/Http/Controllers/ImportController.php
>              }
Great suggestion! I'll look into that. Thanks!

2022-08-18 09:24 UTC, eronisko commented on resources/views/imports/form.blade.php
> +			{!! Form::text('name', Request::old('name'), array('class' => 'form-control', 'placeholder' => '', 'disabled' => !$can_update)) !!}
If it's a view variable, I'd say it should mainly make sense in the view. But on a second look `$disabled` is not the best name either (because we're only disabling some fields, not the entire form), maybe something like `$disabled_metadata_fields` 🤷‍♂️

2022-08-19 06:32 UTC, eronisko approved these changes
Looks good, thank you.

2022-08-19 08:00 UTC, merged