Remove author constraint from Item::related scope
SlovakNationalGallery/webumenia.sk pull request #754
Opened 2022-08-26 11:53 UTC by eronisko

in order to match catalog search Elastic query

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2022-09-06 13:37 UTC, igor-kamil requested changes
see comment

2022-09-06 13:37 UTC, igor-kamil commented on app/Item.php
> -            ->where('author', '=', $item->author)
this is not a proper fix
first of all... `related_work` might be very vague (e.g. `skicár`) and you wouldn't get the same amount of results in artwork detail and in catalogue view (e.g. https://www.webumenia.sk/katalog?related_work=skicár&author=Novák%2C%20Ján vs https://www.webumenia.sk/katalog?related_work=skicár ).

I think the point is to unify the query to get the same results. Hence I suggest to follow  https://github.com/SlovakNationalGallery/webumenia.sk/blob/develop/resources/views/dielo.blade.php#L315-L316 (which gets better results - since it's using only `first_author`)

And fix it with something like
```
        return $query->whereTranslation('related_work', $item->related_work)
            ->where('author', 'like', $item->first_author . '%')
            ->orderBy('related_work_order');
```
or 
```
        return $query->whereTranslation('related_work', $item->related_work)
            ->where('author', 'like',  '%' . $item->first_author . '%')
            ->orderBy('related_work_order');
```

2022-09-16 09:09 UTC, eronisko commented on app/Item.php
> -            ->where('author', '=', $item->author)
Thanks for the pointers. I've tried making this into a `LIKE` query just now and while it works, it always takes over a second to run.

Not sure if this is the right avenue now, seems like a job for ES in this case (the zoom controller is the only place using this query anyway)

2022-09-22 15:07 UTC, eronisko commented on app/Item.php
> -            ->where('author', '=', $item->author)
Re-worked this so that it does an ES search before retrieving items from DB

2022-10-06 09:55 UTC, eronisko commented
@igor-kamil @FrantisekMichalSebestyen @rastislav-chynoransky This is finally passing tests, so ready for another review :)

2022-10-13 09:27 UTC, igor-kamil approved these changes
LGTM

2022-10-13 09:27 UTC, igor-kamil commented on app/Item.php
> +            ->keys();
🙌

2022-10-13 11:31 UTC, merged