feat: parse article from admin to display article-thumbnail
SlovakNationalGallery/webumenia.sk pull request #763
Opened 2022-09-14 09:24 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2022-09-22 09:13 UTC, igor-kamil reviewed
looks nice. since this is somehow defining the way we are going to use components within article/collection content - it's good to design it well. 
I think you can turn PR from draft to regular PR and I would like to see CR from @eronisko

2022-09-22 09:13 UTC, igor-kamil commented on app/Http/Controllers/ClanokController.php
> +        $article->content = Blade::render($this->replaceTags("$article->content"));
what do you @eronisko think about this? 
probably it's ok - since we have control of the article content (it's not from unknown users)

however I would consider something like:
```
        $html = Str::of($html)->replaceMatches('/[ article_thumbnail id="(.*)" \/]/', function ($match) {
                if (empty($match[1])) return '';
​
                $article = Article::find($match[1]);
                $article_thumbnail = view('components.x-article_thumbnail')
                   ->with('media', $article)
                   ->render();
                return $article_thumbnail;
            });
```

(proposed code is not tested... just wrote here)

ta avoid launching any unexpected php code from the content

2022-09-22 09:13 UTC, igor-kamil commented on public/ckeditor/plugins/thumbnail/lang/cs.js
> +        idRequired: 'Prosím zadefinujte id ukazky (číslo)',
```suggestion
        idRequired: 'Prosím zadefinujte id článku (číslo)',
```

2022-09-22 09:13 UTC, igor-kamil commented on public/ckeditor/plugins/thumbnail/lang/sk.js
> +        idRequired: 'Prosím zadefinujte id ukážky (číslo)',
```suggestion
        idRequired: 'Prosím zadefinujte id článku (číslo)',
```

2022-09-28 23:22 UTC, rastislav-chynoransky commented on app/Http/Controllers/ClanokController.php
> +        $article->content = Blade::render($this->replaceTags("$article->content"));
Yes, please, don't interpret the user input. That might quite easily cause errors (since blade syntax could be part of the text).

2022-09-29 07:00 UTC, eronisko requested changes
First of all sorry for responding to this so late. I actually had a comment drafted up for 7 days but haven't been able to finish it until now.

I think the approach with square brackets is sound, but I'd defer from creating any generic solutions at all. I have two possible variants in mind

## Tag with an ID
Similar to what is proposed here, I'd suggest a syntax like this:
```
[ArticleTeaser id=123]
```

Where `id` would be the only supported attribute and I'd parse it like this:
1. Look for something like `[ArticleTeaser .*]` using regex
2. Extract only the supported attributes (`id`)
3. Turn it into a Blade expression

A good tip might be replacing `[ ]` with `< />` (similar to the proposed solution) and then using a HTML parser to extract the attributes.

## Simple tag, no attributes
The disadvantage of the solution above is that at some point we'd have to query the database from a Blade component, which is not a good practice.

If all we need is a teaser to a single article, we can define an "teaser article" attribute on the main object within the admin interface (e.g. `teaser_article_id`) and all we have to do then is to insert `[ArticleTeaser]` somewhere in the text. So the custom block would just serve as a "HERE" pointer for the rendering mechanism, whereas all the data querying would happen outside.

Another advantage of this approach is that we can implement some outside logic for deciding which teasers to show. A disadvantage would be perhaps less flexibility for each article.

2022-09-29 12:09 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail.blade.php
> +
You're right personally, I would make two separate components. If it's alright. The reasoning behind it is that the logic (things supposed to be displayed, what is clickable) changes between these two and I do not expect that the wrapper will be reused on some other page.

2022-09-29 12:16 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +
Cool, sounds good :)

2022-10-11 07:03 UTC, igor-kamil commented
I vote for "_Tag with an ID_" as @eronisko proposed. 
I see it as the most flexible option - and also quick to implement.

2022-10-11 20:50 UTC, FrantisekMichalSebestyen commented
@eronisko @igor-kamil  please review the proposed solution - "Tag with id". Keep in mind that style article teaser is in another PR

2022-10-12 11:48 UTC, igor-kamil reviewed
it looks good! almost there 👍 
I have few comments, but I don't see any real blocker from my point of view

2022-10-12 11:48 UTC, igor-kamil commented on resources/views/frontend/articles/show.blade.php
>                  </div>
In case you renamed the method to `getParsedContentAttribute()` 
you can use:

```suggestion
                    {!! $article->parsed_content !!}
                </div>
```

2022-10-12 11:48 UTC, igor-kamil commented on app/Article.php
> +            $article = Article::find($id);
just put id into parenthesis in the regexp above and use

```suggestion
            $article = Article::find($match[1]);
```

2022-10-13 07:13 UTC, eronisko requested changes
The regexes need a bit more work, but we're getting there :)

> Keep in mind that style article teaser is in another PR

If this PR doesn't deliver a full feature, then please don't merge it into a develop -- make a 'feature' branch instead. Merge your different PRs into that and then we'll merge it into develop all at once.

Whatever is merged to develop should be ready to go to prod at any time.

2022-10-13 07:13 UTC, eronisko commented on app/Article.php
> +            $article = Article::find($id);
It should also only filter published articles (please add a scope)

2022-10-13 07:13 UTC, eronisko commented on public/ckeditor/plugins/articleTeaser/lang/sk.js
> +        idRequired: 'Prosím zadefinujte id článku (číslo)',
```suggestion
        idRequired: 'Zadajte id článku (číslo)',
```

2022-10-20 09:11 UTC, eronisko commented on app/Article.php
> +            $article_teaser = Blade::render('<x-article_teaser :article="$article" :url="$url" />', ['article' => $article, 'url' => $article->getUrl()]);
```suggestion
            $article_teaser = Blade::render('<x-article_teaser :article="$article" />', ['article' => $article]);
```

2022-10-20 11:10 UTC, eronisko approved these changes
LGTM, thank you :)

2022-10-20 11:10 UTC, eronisko commented on CHANGELOG.md
> +- parse article teaser from admin
This should come under 'Unreleased'

2022-10-20 11:27 UTC, merged