Webumenia 819 store and display vp start date and vp end date fo
SlovakNationalGallery/webumenia.sk pull request #765
Opened 2022-09-14 14:48 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

<img width="926" alt="Snímka obrazovky 2022-09-14 o 16 43 33" src="https://user-images.githubusercontent.com/28804184/190187772-7f194d7a-467d-4e18-878d-d254be049a34.png">

2022-09-28 12:20 UTC, DigitalArtsAFAD commented
what's next? @mcudrnak @FrantisekMichalSebestyen ?

2022-09-29 08:09 UTC, eronisko requested changes
The fact that we've created 3 static functions (but we're only using one of them) hints to me that this perhaps doesn't belong to Authority and it's more presentation-related.

I'd suggest moving this into a [Blade component](https://laravel.com/docs/9.x/blade#components). (You can also [define methods there](https://laravel.com/docs/9.x/blade#component-methods))

2022-09-29 08:11 UTC, eronisko commented
Please also check if your Prettier is on (it doesn't seem to be)

2022-09-29 11:12 UTC, FrantisekMichalSebestyen commented
> Please also check if your Prettier is on (it doesn't seem to be)

You're right, I'm just confused what it the policy for formatting now? 
Should I at the end make commit formatting all affected files ?

2022-09-29 11:13 UTC, FrantisekMichalSebestyen commented on app/Authority.php
> +        $activity = self::formatActivity(self::formatMultiAttribute($event->event));
I felt like inlining the function into blade component was a bit overwhelming to read, but I will move it.

2022-09-29 11:18 UTC, eronisko commented
> > Please also check if your Prettier is on (it doesn't seem to be)
> 
> You're right, I'm just confused what it the policy for formatting now? 

I wouldn't call it a "policy" but I usually 

* format everything (prettier) if I've made big changes
* not format if I've only changed a few lines in an unformatted file

> Should I at the end make commit formatting all affected files ?

That's a good idea if you can put those changes in a 'formatting-only' commit. Preferably at the start, though.

The Right Solution™ I guess is to just format everything as we discussed on Slack.

2022-10-06 11:20 UTC, eronisko requested changes
Almost there

2022-10-06 11:20 UTC, eronisko commented on resources/views/components/authority-event.blade.php
> +        href="{!! route('frontend.author.index', ['place' => $event->place]) !!}">{!! $event->place !!}</a></strong>{{ $formatEvent($event) }}{{ $i + 1 < $count ? ', ' : '' }}
Let's move `{{ $i + 1 < $count ? ', ' : '' }}` out of here, there's no need to for this component to be concerned with its outside context. (Don't forget to remove attributes from `@props` too)

2022-10-06 12:08 UTC, FrantisekMichalSebestyen commented on app/View/Components/AuthorityEvent.php
> +            : $activityTranslation;
They are not equal, tho. The recommended solution does not work for authorities, that only have one translated "role".

2022-10-07 06:34 UTC, eronisko commented on app/View/Components/AuthorityEvent.php
> +            : $activityTranslation;
You're right, thanks

2022-10-07 07:54 UTC, FrantisekMichalSebestyen commented
@eronisko ready for review

2022-10-07 18:03 UTC, merged