style: article thumbnail component
SlovakNationalGallery/webumenia.sk pull request #766
Opened 2022-09-19 08:55 UTC by FrantisekMichalSebestyen

# Description

Style article thumbnail component inside list
I will follow article thumbnail component inside article in another PR

SM: 
<img width="463" alt="Snímka obrazovky 2022-09-19 o 10 52 19" src="https://user-images.githubusercontent.com/28804184/190982600-f8514457-370f-44a1-aa4c-c408c3dc29f1.png">

MD:
<img width="504" alt="Snímka obrazovky 2022-09-19 o 10 52 47" src="https://user-images.githubusercontent.com/28804184/190982632-aee1c3ca-ae9a-49be-b003-88f316979782.png">

 
LG:
<img width="1237" alt="Snímka obrazovky 2022-09-19 o 10 52 02" src="https://user-images.githubusercontent.com/28804184/190982660-3d50d325-4a5b-4c73-9f9c-c251cdbf43d3.png">

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [x] I have made corresponding changes to the documentation

2022-09-22 08:46 UTC, eronisko requested changes
Thanks. Code-wise this looks good, except for a few notes, mostly for code carried over from the old component.

I'm not sure whether the design will work well with the data we have today (I don't think the current thumbnail resolution will be sufficient). But that would be for a discussion elsewhere.

2022-09-22 08:46 UTC, eronisko commented on resources/views/components/article_thumbnail_index.blade.php
> +        class="tw-container tw-mx-auto tw-flex tw-h-[475px] tw-max-w-screen-xl tw-flex-wrap tw-px-6 tw-py-4 md:tw-h-[400px] md:tw-flex-nowrap md:tw-py-8">
Please specify the custom heights in `rem` rather than `px`. 

(Almost everything in Tailwind is in rem, e.g. https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale)

2022-09-22 08:46 UTC, eronisko commented on resources/views/components/article_thumbnail_index.blade.php
> +$showEduTags = $showEduTags ?? false;
Please turn these into `@props`: https://laravel.com/docs/9.x/blade#data-properties-attributes

`$article` should be included in the `@props` list too, that way we should get errors earlier.

2022-09-22 08:46 UTC, eronisko commented on resources/views/components/article_thumbnail_index.blade.php
> +                    <img src="{!! $article->getThumbnailImage() !!}"
As long as `getThumbnailImage` is returning a non-html string, we don't have to use the `{!! !!}` brackets
```suggestion
                    <img src="{{ $article->getThumbnailImage() }}"
```

2022-09-22 08:46 UTC, eronisko commented on resources/views/components/article_thumbnail_index.blade.php
> +                {!! $article->created_at->format('d. m. Y') !!}
I'd use the `@date` or `@dateShort` directive (from AppServiceProvider) here, to keep the date format consistent with other places.

(Also no need for `{!!`)

2022-09-22 08:46 UTC, eronisko commented on resources/views/frontend/articles/index.blade.php
> +    <div class="tailwind-rules">
Do we need this wrapping div here?

2022-09-22 08:46 UTC, eronisko commented on resources/views/components/article_thumbnail_index.blade.php
> +@php
I'd suggest re-using the `article_thumbnail` name, especially since we're deleting the old component. The `_index` suffix does not add any more information IMHO.

2022-09-22 08:56 UTC, igor-kamil commented on resources/views/components/article_thumbnail_index.blade.php
> +@php
I think I see the reason (because there is going to be another article_thumbnail inside article)
However I prefer to keep it consistent with previous code... please don't rename (until really necessary)

2022-09-22 09:24 UTC, eronisko commented on resources/views/components/article_thumbnail_index.blade.php
> +                    <img src="{!! $article->getThumbnailImage() !!}"
Please take a look at `HasHeaderImage#getThumbnailImage` -- we might have to change the resolution for thumbnails if we want them larger

2022-09-25 08:15 UTC, eronisko commented on resources/views/components/article_thumbnail_index.blade.php
> +                {!! $article->created_at->format('d. m. Y') !!}
That's not necessary in my opinion (let's keep the PR lean)

2022-09-25 16:31 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail_index.blade.php
> +                    <img src="{!! $article->getThumbnailImage() !!}"
Yes, true. Also, we should note somewhere, that we will need to rerender old article thumbnails at some point.

2022-09-25 17:30 UTC, FrantisekMichalSebestyen commented
> from my point of view... there are two (visual) issues. first is hard-cutting the overflowed text <img alt="Snímka obrazovky 2022-09-21 o 11 56 53" width="360" src="https://user-images.githubusercontent.com/2682941/191704358-8e68ffdf-8dd8-4f63-b63c-0051e27256e9.png">
> 
> try to set height to avoid cutting the line (and test it for all breakpoints) - I think it might be possible second option is to apply "fade-out" with gradient (similar what used to seen on paywalls)
> 
> second issue is spacing. it simply doesn't follow the proposed design: <img alt="190982660-3d50d325-4a5b-4c73-9f9c-c251cdbf43d3" width="1237" src="https://user-images.githubusercontent.com/2682941/191705217-7af52e70-a566-4299-a809-a0bb7c028cd1.png">
> 
> vs
> 
> <img alt="Snímka obrazovky 2022-09-22 o 11 00 14" width="768" src="https://user-images.githubusercontent.com/2682941/191705238-2e82e3e0-2097-4525-bdac-dbe61609a64b.png">

I was thinking about this and there are simply too much variables: 
1. Category is either there or not 
2. Title is from 1 to 3 lines
3. and ofc the breakpoints
I pushed the fade out but will consult @memb

2022-09-29 08:56 UTC, eronisko reviewed
Code-wise this looks fine (just please render the "thumbnail" image as a responsive image)

In terms of design, I'm not sure. Still think think this typography is a bit too generous:
![image](https://user-images.githubusercontent.com/1374745/192987881-79b9c3f9-d8f4-46ee-8046-2cf41ab30a1f.png)

2022-09-29 08:56 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +    'article' => null,
```suggestion
    'article',
```

2022-09-29 08:56 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +    'url' => $article->getUrl(),
Does this work? (It seems that we're defining and using the`$article` variable in one statement, so it's an honest question)

A good test would be to re-name the `article` prop to something else

2022-09-29 08:56 UTC, eronisko commented on app/Concerns/HasHeaderImage.php
> +                \Image::make($full_path)->fit(1200, 480)->save($preview_full_path);
On a second thought, we'll probably need this for the mobile layout, so please roll this back to 600+250 -- sorry

2022-09-29 08:56 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +                    <img src="{{ $article->getThumbnailImage() }}"
We should incorporate the thumbnail image size into a [responsive image](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) attribute (`srcset`)

Please either include the thumbnail size in `HasHeaderImage#getHeaderImageSrcsetAttribute` or suggest a new method to generated `srcset` for the thumbnail `img` tag.

2022-09-29 09:28 UTC, eronisko commented
I've deployed the PR to test:

```
 dep deploy test --branch WEBUMENIA-1558-article-thumbnail-component
```

@ustengrav @igor-kamil , can you please take a look?

2022-09-29 10:15 UTC, FrantisekMichalSebestyen commented
@eronisko Sorry you are right about the typograhpy on mobile I somehow missed it. Fixed it in new commit

2022-09-29 10:18 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail.blade.php
> +    'url' => $article->getUrl(),
It should. We are not passing url attribute in `_frontend/articles/index.blade.php_ `, but we are able to click on image to get in the article.

2022-09-29 10:41 UTC, eronisko reviewed
![image](https://user-images.githubusercontent.com/1374745/193010697-b649fe06-46c2-4e4d-8b48-eb9ae9db77e6.png)

The author is underlined on hover, but it's not a link. Not sure what the desired state is.

2022-09-29 10:43 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +            <div class="text-2xl tw-pb-2 tw-font-semibold md:tw-text-4xl">
Please take a look at the `text-2xl` class (it should be `tw-text-2x`)

2022-09-29 11:05 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail.blade.php
> +            <div class="text-2xl tw-pb-2 tw-font-semibold md:tw-text-4xl">
I will ask memb about the underline

2022-09-29 14:25 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +                <div class="tw-pb-3 tw-text-sm tw-font-medium tw-text-gray-600 md:tw-text-lg">
Please add `capitalize`

2022-09-29 20:33 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail.blade.php
> +                <div class="tw-pb-3 tw-text-sm tw-font-medium tw-text-gray-600 md:tw-text-lg">
Are you sure ? We don't do it anywhere else

2022-09-29 20:36 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail.blade.php
> +                <div class="tw-pb-3 tw-text-sm tw-font-medium tw-text-gray-600 md:tw-text-lg">
Can it be that data in test databse are different than the ones on production ? therefore category is lowercase

2022-09-30 07:37 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +                <div class="tw-pb-3 tw-text-sm tw-font-medium tw-text-gray-600 md:tw-text-lg">
We're capitalizing first letter here https://github.com/SlovakNationalGallery/webumenia.sk/blob/develop/resources/views/home/index.blade.php#L278 for example. But using the CSS class is more elegant IMHO

2022-09-30 10:28 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail.blade.php
> +                    <img srcset="{{ $article->getHeaderImageSrcsetAttribute() }}"
this should be enough right ? @eronisko since the width of image is determined by flexbox

2022-10-06 08:54 UTC, FrantisekMichalSebestyen commented on resources/views/components/article_thumbnail.blade.php
> +                <div class="tw-pb-3 tw-text-sm tw-font-medium tw-text-gray-600 md:tw-text-lg">
tw-capitalize capitalizes first char of every letter, therefore i used Str::ucfirst

2022-10-06 11:51 UTC, eronisko requested changes
I don't mean to stand in the way of progress. Code-wise, I think this looks good. The design (implementation?) needs still needs some work here. 

This still looks broken:
![image](https://user-images.githubusercontent.com/1374745/194304008-10855542-2e47-44ff-84bf-1e036e361067.png)

I offer https://tailwindcss.com/blog/multi-line-truncation-with-tailwindcss-line-clamp up for consideration.

At certain resolutions, this just doesn't look very good:

### 768px
![image](https://user-images.githubusercontent.com/1374745/194304495-18c6dd48-96e6-49f9-8674-0c0cc3a87628.png)

### ~700px
(this I could live with, but wanted to point out)
![image](https://user-images.githubusercontent.com/1374745/194304947-ef3db6e3-b67e-4c27-b6b1-2200efa24dfe.png)

### 320px
keeps cutting off last line
![image](https://user-images.githubusercontent.com/1374745/194305159-7135116b-23ed-4423-9f3f-db3c7bea806a.png)

Feel free to reach out to myself, @igor-kamil or @ustengrav, if you want to discuss how to solve some of these issues.

2022-10-06 11:51 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +                        sizes="(max-width: 768w) 100vw, 50vw"
The thumbnails are kinda blurry at ~1024px width. 

Compare 

```
sizes="(max-width: 768w) 100vw, 50vw"
```
![image](https://user-images.githubusercontent.com/1374745/194302804-fa5e221b-daa6-4462-9811-7de83f8b4b2c.png)

to

```
sizes="(max-width: 768w) 100vw, 150vw"
```
![image](https://user-images.githubusercontent.com/1374745/194302822-18dd1ac4-2ec6-49a5-ac83-f288bbba0f3a.png)

2022-10-06 11:53 UTC, eronisko commented on resources/views/components/article_thumbnail.blade.php
> +                        sizes="(max-width: 768w) 100vw, 50vw"
Note that yes, the image is only ~50% of the screen, but because its height (not width) is specified here, sometimes it needs to stretch beyond 100% of screen size

2022-10-21 06:55 UTC, eronisko commented
Since don't have a home for this yet, I'd suggest closing this PR (but leaving the branch as is)

2022-10-21 17:32 UTC, closed without merging