[import] use flysystem storages
SlovakNationalGallery/webumenia.sk pull request #781
Opened 2022-10-24 23:23 UTC by rastislav-chynoransky

https://jira.sng.sk/browse/PNP-73

2022-10-27 10:42 UTC, eronisko requested changes
This is a nice improvement, and I'm looking forward to it. I have some comments mostly to do with naming, but I'm also not able to run the tests locally. I get this message:

```
  Unable to read file from location: .
```

Can you please help me debug or (better) make it so that I don't have to add/change anything in order to run the tests locally? (Currently the tests are working for me against `develop` branch)

2022-10-27 10:42 UTC, eronisko commented on .env.example
> +DG_PUBLIC_IS_PATH=
Could you please pick a more verbose name for this? I don't know that `DG` or `IS` is

2022-10-27 10:42 UTC, eronisko commented on config/filesystems.php
> +        'DG_PUBLIC_IS' => [
Same as above -- can you please name this more generously? :)

2022-10-27 10:42 UTC, eronisko commented on database/migrations/2022_10_25_104407_add_disk_to_imports_table.php
> +            $table->string('disk')->default('import');
Here I would strongly prefer setting the default in either code or a config file.

2022-10-27 10:42 UTC, eronisko commented on tests/Importers/WebumeniaMgImporterTest.php
> +        $storage->put('rada_s000123-lomeni_s.jp2', '');
It's not obvious to me why & when this file needs to exist

2022-10-27 11:36 UTC, rastislav-chynoransky commented on database/migrations/2022_10_25_083719_cleanup_import_records_table.php
> +                ->default(0)
Here I wanted to align it with the other columns `imported_iip` and `wrong_items`. And since the columns are not nullable it seemed like reasonable default for the schema. I'm also ok with creating `ImportRecordFactory` for this purpose, but I find it unnecessary for such primitive defaults.

2022-10-27 11:38 UTC, rastislav-chynoransky commented on app/Importers/PnpKarasekImporter.php
> +    public function import(Import $import, SplFileInfo $file): array
Not sure if I get you right, but the overriding definition must follow that one of the parent method.

2022-10-27 11:43 UTC, rastislav-chynoransky commented on config/filesystems.php
> +        'DG_PUBLIC_IS' => [
The name exactly refers to the name of the folder on `imi` server. I was considering naming it `imi` disk, however we're not mounting/referencing the whole `imi` server, only this folder. I think it best describes what it is but I'm open to your suggestions. @igor-kamil had the same comment.

2022-10-27 11:46 UTC, rastislav-chynoransky commented on tests/Importers/WebumeniaMgImporterTest.php
> +        $storage->put('rada_s000123-lomeni_s.jp2', '');
In `WebumeniaMgImporter` we're importing only those items that have some associated JP2 images therefore the dependency on filesystem.

2022-10-27 11:47 UTC, eronisko commented on database/migrations/2022_10_25_083719_cleanup_import_records_table.php
> +                ->default(0)
OK. If other column defaults are set in DB too then I guess it's better to be consistent.

I'm just not a fan of setting non-trivial defaults (anything other than e.g. `0`, or `false`) in DB because it's hard to find them later and any changes will require more DB migrations.

FYI, I don't think it would be necessary to reach for a factory right away, there's a way to [set attribute defaults in Laravel](https://laravel.com/docs/9.x/eloquent#default-attribute-values)

2022-10-27 11:50 UTC, eronisko commented on app/Importers/PnpKarasekImporter.php
> +    public function import(Import $import, SplFileInfo $file): array
I probably asked in the wrong place. Is there much added value in defining the return type in `AbstractImporter::import`?
Can't your IDE/editor figure out what the type will be?

Here's an example without annotation
![image](https://user-images.githubusercontent.com/1374745/198276814-a8979163-69dd-4c3a-81f8-d9298d932a71.png)

2022-10-27 12:01 UTC, rastislav-chynoransky commented on app/Importers/PnpKarasekImporter.php
> +    public function import(Import $import, SplFileInfo $file): array
I think it's the best practice to use typed definitions, but I'm open to discussion.

2022-10-27 12:02 UTC, rastislav-chynoransky commented on database/migrations/2022_10_25_083719_cleanup_import_records_table.php
> +                ->default(0)
I didn't know about them, thanks!

2022-10-28 09:35 UTC, eronisko commented on config/filesystems.php
> +        'DG_PUBLIC_IS' => [
Well, I don't know what the `imi` server is either :D How about something like `JP2_IMAGES_DIR`? Is it the same as the IIP server? Then maybe `IIP_IMAGES_DIR`?

2022-10-28 09:43 UTC, eronisko commented on config/filesystems.php
> +        'DG_PUBLIC_IS' => [
Or even IMPORT_IMAGES_DIR... the fewerabbreviations the better.

2022-10-28 09:46 UTC, rastislav-chynoransky commented on config/filesystems.php
> +        'DG_PUBLIC_IS' => [
That’s the thing that we’re moving csv and jpeg files there as well. We can still call it `imi` disk (as is the name of the mounted server), but I’ve mentioned why I didn’t so.

2022-10-30 19:23 UTC, eronisko approved these changes
Looks good to me and tests are passing locally no problem.

Thank you very much for all the changes. 

🚀

2022-10-30 19:23 UTC, eronisko commented on storage/framework/testing/.gitignore
> +!.gitignore
This is probably no longer required

2022-10-30 20:25 UTC, rastislav-chynoransky commented on storage/framework/testing/.gitignore
> +!.gitignore
Not required but it follows the current framework template so I'd keep it there.

2022-10-30 20:27 UTC, merged