Webumenia 1900 UI pre panel filtrov
SlovakNationalGallery/webumenia.sk pull request #790
Opened 2022-11-19 20:53 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2022-11-24 08:06 UTC, eronisko requested changes
Looking good, just some minor suggestions

2022-11-24 08:06 UTC, eronisko commented on resources/js/components/catalog-new/ShowMore.vue
> +            @click="controller.toggleIsExtendedOpen"
Do we really need to inject the controller here? I'd handle the state locally (in `data` in this component)

2022-11-24 08:06 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                            placeholder="Napíšte meno autora / autorky">
```suggestion
                        <filter-new-custom-select name="authors"
                            placeholder="Napíšte meno autora / autorky">
```

2022-11-25 08:21 UTC, eronisko commented on resources/js/components/catalog-new/Filter.vue
> +        },
```suggestion
        selectedValues() {
            return {
              ...this.$route.query,
              authors: typeof $this.route.query.authors === "string" ? [$this.route.query.authors] : $this.route.query.authors
            }
        },
```

2022-11-25 09:22 UTC, eronisko requested changes

2022-11-25 12:32 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/NewCustomCheckbox.vue
> +    <label class="tw-flex tw-items-center tw-font-normal" :for="title">
there is a css style coming from somewhere setting label it to bold 🤷

2022-11-25 13:39 UTC, merged