feat: add sort
SlovakNationalGallery/webumenia.sk pull request #791
Opened 2022-11-19 20:54 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2022-11-24 08:14 UTC, eronisko requested changes

2022-11-24 08:14 UTC, eronisko commented on resources/js/components/catalog-new/Filter.vue
> +        },
No need for a computed property _and_ a method -- I'd suggest moving the contents of `getSort` here

2022-11-24 08:14 UTC, eronisko commented on resources/js/components/catalog-new/Filter.vue
> +            ).length
Again, pls extract from URL -- looks like we'll need a `selectedValues` computed property

2022-11-24 08:14 UTC, eronisko commented on resources/js/components/catalog-new/Filter.vue
> +            return urlQuery['sort'] || 'updated_at'
It's fine to leave `sort` null/empty -- usually we'd handle default sorting on the back-end anyway. No need for a default on the front-end

2022-11-24 08:14 UTC, eronisko commented on resources/js/components/catalog-new/Filter.vue
> +        handleSort(sortValue) {
```suggestion
        handleSortChange(sortValue) {
```

2022-11-24 08:14 UTC, eronisko commented on resources/js/components/catalog-new/NewSort.vue
> +            ]
Pls pass these as props (can be a static object for now no prob)

2022-11-25 08:14 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/Filter.vue
> +            ).length
Fixed in previous PR

2022-11-25 12:02 UTC, eronisko approved these changes
LGTM, thanks :)

2022-11-25 13:32 UTC, merged