style: mobile filter
SlovakNationalGallery/webumenia.sk pull request #816
Opened 2023-02-28 20:15 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2023-02-28 20:20 UTC, FrantisekMichalSebestyen commented on resources/less/custom.less
> +        z-index: 10;
hopefully i did not break anything

2023-03-02 07:09 UTC, eronisko commented on resources/js/components/catalog-new/DisclosureFilterView.vue
> +                    <div class="tw-flex">
I think you can just put `tw-flex` on the parent button, no?

2023-03-02 07:09 UTC, eronisko commented on resources/js/components/catalog-new/DisclosureFilterView.vue
> +                <button
Please give this more vertical padding
<img width="126" alt="image" src="https://user-images.githubusercontent.com/1374745/222354569-cd02889c-c349-434a-8ada-43784612fa28.png">

2023-03-02 07:09 UTC, eronisko commented on resources/js/components/catalog-new/DisclosureFilterView.vue
> +        <div class="tw-mx-4 tw-my-6 tw-flex tw-justify-between tw-items-center">
The proportions seem a little off here. Look at spaces around search bar and typography.

Compare this
<img width="492" alt="image" src="https://user-images.githubusercontent.com/1374745/222355197-7970b70c-20ea-4f59-967f-301c2848a3a6.png">

with Figma
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1374745/222355589-aa036dd4-c347-48b3-b554-d2155adbc820.png">

2023-03-02 07:09 UTC, eronisko commented on resources/js/components/catalog-new/DisclosureFilterView.vue
> +        <div class="tw-mx-4 tw-my-6 tw-flex tw-justify-between tw-items-center">
The icons also don't look quite right -- the line-icons (font-awesome) are just a different style and a different weight. Could we try using heroicons instead to see if it looks better?

2023-03-09 07:38 UTC, eronisko requested changes
It looks good but please adjust the icons like we discussed last week -- either use Heroicons/Phosphor so that we have a consistent icon set meaning same height/width and consistent style.

We're building a new collection of patterns and we want it to be consistent. So exporting from Figma is last resort; the icons would have to be prepared as a set.

2023-03-09 11:12 UTC, eronisko approved these changes

2023-03-09 11:12 UTC, eronisko commented on resources/js/components/catalog-new/DisclosureFilterListButton.vue
> +            height="16"
```suggestion
            class="tw-ml-4 tw-h-4 tw-w-4"
            xmlns="http://www.w3.org/2000/svg"
```

2023-03-10 07:35 UTC, merged