Webumenia 1904 - Pagination + a bit of mansonry
SlovakNationalGallery/webumenia.sk pull request #825
Opened 2023-03-16 15:25 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2023-03-17 06:39 UTC, eronisko requested changes
Nice to see this work! I just have some code organization/naming notes.

2023-03-17 06:39 UTC, eronisko commented on resources/js/app.js
> +Vue.component('filter-masonry', require('./components/catalog-new/ArtworksMasonry.vue').default);
```suggestion
Vue.component('items-masonry', require('./components/catalog-new/ItemsMasonry.vue').default);
```

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkImage.vue
> +                    ? `hsl(${hsl[0].h}, ${hsl[0].s}%, ${hsl[0].l}%)`
Please pass just one color as the prop so we don't have to look up `[0]` everywhere

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkImage.vue
> +                    : '#cdcdcd',
This could be set in a css class instead

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkImage.vue
> +        ratio: Number,
```suggestion
        aspectRatio: Number,
```

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkImage.vue
> +        src: String,
It would be also good to add `srcSet` here

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkImage.vue
> +        hsl: Array,
```suggestion
        placeholderColorHsl: Object 
```

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworksMasonry.vue
> +            <button :class="{ 'tw-invisible': this.page }" ref="more" @click="$emit('loadmore')">
```suggestion
            <button v-if="this.page" ref="loadMoreButton" @click="$emit('loadmore')">
```

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworksMasonry.vue
> +        url: String,
Please pick a more specific name, it's not clear what `url` this is.

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ArtworksMasonry.vue
> +            <button :class="{ 'tw-invisible': this.page }" ref="more" @click="$emit('loadmore')">
IMHO this button does not need to be a part of this component. It could be a separate "loadMore" component that both renders the button and does the auto-load.

And then we can actually take everything else from ArtworksMasonry out and into the Blade template.

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +                    this.page = null
When I see a side-effect like this, that's usually a sign that something is not quite right.

I would expect something like:
```js
const artworks = await axios.get(...)
const filters = await axios.get(...)

if (append) {
  this.artworks = [...this.artworks, ...artworks]
  this.filters = [...this.filters, ...filters]
  return
}

this.artworks = artworks
this.filters = filters
```

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +        },
Wouldn't the data get fetched twice? This doesn't seem like the right pattern here. This kind of logic should probably happen in `incrementPage` or in the `query` observer

2023-03-17 06:39 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                            @loadmore="incrementPage" :artworks="artworks"></filter-masonry>
```suggestion
                            @loadMore="loadMore" :artworks="artworks"></filter-masonry>
```

2023-03-17 06:39 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +            page: this.page,
I think `page` should be a part of the `query`

2023-03-17 06:40 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                            url="https://www.webumenia.sk/dielo/nahlad/" :page="page"
Please use the Laravel `route` helper here

2023-03-17 07:27 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ArtworksMasonry.vue
> +            <button :class="{ 'tw-invisible': this.page }" ref="more" @click="$emit('loadmore')">
Not gonna work, the element is needed for IntersectionObserver:
However I can do something like this, If you prefer:
```suggestion
            <div ref="loadMoreWrapper"> 
                <button v-if="this.page" ref="loadMoreButton" @click="$emit('loadmore')">
           </div>
```

2023-03-17 07:49 UTC, eronisko commented on resources/js/components/catalog-new/ArtworksMasonry.vue
> +            <button :class="{ 'tw-invisible': this.page }" ref="more" @click="$emit('loadmore')">
Ah, gotcha. Would it work with `v-show`? If not, then let's out the observer on an element that's not designed to hide, like something with zero-height.

2023-03-17 08:04 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +        async fetchData({ replaceArtworks }) {
Maybe separate into two different methods
```
fetchArtworks(append = false)
fetchAggregations()
```

2023-03-17 08:35 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ArtworksMasonry.vue
> +            <button :class="{ 'tw-invisible': this.page }" ref="more" @click="$emit('loadmore')">
not working with `v-show` will use the second option

2023-03-17 13:39 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ArtworkImage.vue
> +        src: String,
I would prefer to do it in separate PR

2023-03-17 13:40 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ArtworkImage.vue
> +        src: String,
the one where i style it and add routing, favs, etc.

2023-03-17 13:41 UTC, FrantisekMichalSebestyen commented on resources/js/app.js
> +Vue.component('filter-masonry', require('./components/catalog-new/ArtworksMasonry.vue').default);
got rid of it completely: Now its just handler of infinite scroll

2023-03-23 06:01 UTC, eronisko requested changes
Some good progress, thanks. I have mostly minor suggestions

2023-03-23 07:09 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ArtworkImage.vue
> +        <img :class="{ 'tw-hidden': !this.isLoaded }" @load="onImgLoad" :src="imageSrc" />
Is done in #826

2023-03-23 07:21 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +            isFetchingArtworks: false,
Hm... I do not think it is used but, it might be needed for someone using the component, 🤷 Tbh, we should also do error handling. (we can talk about it). So you think i should get rid of is (fetchingArtworks completely) Or add loading insided the filters with aggregations ?

2023-03-23 08:22 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkImage.vue
> +        <img :class="{ 'tw-hidden': !this.isLoaded }" @load="onImgLoad" :src="imageSrc" />
And you did mention that previously, sorry

2023-03-23 08:32 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +            isFetchingArtworks: false,
The ItemsFilterController is a very specific (non-reusable) component so it'll most likely only be used where it is used currently.

The point I was trying to make is that unless we actually need that variable, I wouldn't even create it. If we need it in the future, it's easy to add. But if we end up not using it, it's not easy to remember to delete it, and we're effectively creating technical debt.

Error handling -- I agree, but that would have to be done in a separate task since it's not designed right now.

2023-03-24 10:17 UTC, eronisko approved these changes
Looking good, thanks

2023-03-24 11:34 UTC, merged