Masonry tile
SlovakNationalGallery/webumenia.sk pull request #826
Opened 2023-03-20 22:06 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2023-03-22 15:43 UTC, FrantisekMichalSebestyen commented
@eronisko Sorry, I cannot test it properly, i do not have image-previews locally. We tried to fix it with igor, but it did not work. Could you help me?

2023-03-23 09:46 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                        </user-collections-favourite-button>
Making the icons pluggable (into slots) is not the right approach in my opinion. It adds unnecessary complexity.

The component itself is so simple I'd just make a `FavouriteButtonV2` copy component with the right icons. We could DRY up the business logic there, but I don't think it's worth the effort in this case.

2023-03-23 09:46 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                        {!! route('dielo.nahlad', ['id' => '__ARTWORK_ID__', 'width'=>'800']) !!} 800w"
Are the `{!! !!}` really necessary here?
Also, the image width (e.g. `220`) is probably not the same as screen width (e.g. `220w`) if we're showing the images in columns.

2023-03-23 09:46 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkTile.vue
> +                    : '#cdcdcd',
CSS class? :)

2023-03-23 09:46 UTC, eronisko commented on resources/js/components/catalog-new/ArtworkTile.vue
> +                <slot name="favourite-button"></slot>
This is my beef with Vue components... It's silly to pass the favourite-button through a slot, there's no need for the flexibility -- it should always look/be the same. But we can't just put it in because we don't have translation strings available in Vue. So we either do a slot or we do some prop drilling.

Looking at the props of this component, it really is just concerned with parsing things from Laravel into Vue so I'd suggest skipping that part altogether.

I think it'll be better to make this into either a Blade component or no component (i.e. inline it). I'd keep the `<img` and the placeholder in a Vue component (to keep the interactive feature), and everything else can stay in Blade.

2023-03-28 14:08 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ArtworkImageController.vue
Not sure where to put this. As this will be probably used all over webumenia.

2023-03-29 15:11 UTC, eronisko requested changes
It looks good overall, but I suspect it has some changes carried over from #825.

Please merge/re-base and I'll review again.

2023-03-29 15:11 UTC, eronisko commented on resources/js/components/catalog-new/FavouriteController.vue
We could go one level deeper and instead of exposing `store`, expose `toggleItem`, `hasItem`, etc

2023-03-30 06:26 UTC, eronisko commented on resources/js/components/catalog-new/FavouriteController.vue
Also then it could be called user-collections-store (and be stored as such, under `components/user-collections`)

2023-03-30 06:29 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                                        <svg xmlns="http://www.w3.org/2000/svg"
probably no need for the spans here -- just `v-if` the svg
```suggestion
                                                    <svg v-if="store.hasItem(artwork.id)" xmlns="http://www.w3.org/2000/svg"
```

2023-03-30 11:03 UTC, merged