Webumenia 1925 labels mobile filter
SlovakNationalGallery/webumenia.sk pull request #827
Opened 2023-03-22 15:28 UTC by FrantisekMichalSebestyen

# Description
fix: reset filter on other filters on desktop
fix: reset filter on desktop
feat: add color slider into mobile
feat: rework color slider
style: labels for color + yearRange
fix: year range on created
fix: isExtended open on start

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2023-03-24 21:22 UTC, eronisko reviewed
I think filter-new-selected-labels could be re-worked into the blade template

2023-04-25 17:53 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/NewColorSlider.vue
> +        <slider
I suppose the slider library stopped working after the migration to vue3. Will need to investigate this furthers

2023-05-04 05:53 UTC, eronisko requested changes
I really like those new Blade components and the fact that this change only adds 100 lines of code 👍

I have a few notes (mostly to do with component reusability and extraction of SVGs), but we're close to the finish line now

2023-05-04 05:53 UTC, eronisko commented on package.json
> +        "vue-slider-component": "^4.1.0-beta.7"
Was this update necessary? I'm asking because that component is probably used in production as well. Or am I mistaken? It's not a blocker, we just need to make sure that the upgrade didn't break anything in the prod components.

2023-05-04 05:53 UTC, eronisko commented on resources/js/components/catalog-new/NewColorSlider.vue
> +        <slider
Thank you. Have you managed to fix it?

2023-05-04 05:53 UTC, eronisko commented on resources/js/components/catalog-new/NewColorSlider.vue
> +        hueBgColorFn() {
Please don't add `Fn` to function names 🙏

I can see you were following older code convention but I'd rather have this "convention" changed. Not sure how it got here but I'd probably reviewed it so my bad.

2023-05-04 05:53 UTC, eronisko commented on resources/views/components/filter/disclosure_modal.blade.php
> +<div v-if="{{ $attributes->get('v-if') }}"
This attribute selection is a bit of a gotcha... But the syntax works, so let's try :)

I'd just suggest following the convention of passing (almost) all attributes to the root element:
```suggestion
<div v-if="{{ $attributes->except('@close')->merge(...) }}"
```

2023-05-04 05:53 UTC, eronisko commented on resources/views/components/filter/disclosure_button.blade.php
> +    {{ $attributes }}>
This looks very nice 👍 

But we can't pass any more classes to it right now. We can do this:

```suggestion
<button
    {{ $attributes->merge(['class' => "tw-flex tw-items-center tw-border tw-border-gray-300 tw-bg-white tw-py-2 tw-px-3 tw-text-base tw-font-medium hover:tw-border-gray-800"]) }} >
```

2023-05-04 05:53 UTC, eronisko commented on resources/views/components/filter/disclosure_view.blade.php
> +<div class="tw-grow tw-bg-white tw-flex tw-flex-col" v-if="{{ $attributes->get('v-if') }}">
Same as above -- please use `except` (and `merge`)

2023-05-04 05:53 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                                <svg class="tw-mr-1.5 tw-h-4 tw-w-4 tw-fill-current"
You know me -- I'm not a guy who's afraid of HTML.

But these SVGs are making it a little difficult to see what's going on on the page -- it's impossible to tell what they show and it's hard to see how many times an image is re-used.

I've found 6 usages of this image/icon on this page so this is a good candidate for extraction. My suggestion would be to use a Blade component.

----

If you know an SVG image will be used more than once, I'd err on the side of extracting too soon.

Are there more instances of re-used inlined SVGs? Now is a good time to extract them while you still remember where they are.

2023-05-04 05:53 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                    />
Just double-checking -- has this been optimized?

2023-05-04 08:04 UTC, FrantisekMichalSebestyen commented
https://github.com/SlovakNationalGallery/webumenia.sk/pull/827#discussion_r1184555579
Cannot replay to comment somehow.
Put the issue with slider was resolved in #843

2023-05-05 07:33 UTC, eronisko approved these changes

2023-05-05 07:33 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +                : null,
```suggestion
        yearRange: (() => {
            if (!date_earliest || !date_latest) return null
            return {...}
        })()
```

2023-05-05 07:33 UTC, eronisko commented on resources/js/components/catalog-new/NewColorSlider.vue
> +        hueBgColor() {
Might be better inlined

2023-05-05 07:33 UTC, eronisko commented on resources/views/components/filter/reset_button.blade.php
> +    <span>{{ $slot }}</span>
Would this work?
```suggestion
   {{ $slot }}
```

2023-05-05 07:33 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                            :style="{'background': `#${query['color']}`}">
```suggestion
                                        color
                                        <div v-if="query['color']"
                                            class="tw-inline-block tw-h-4 tw-w-4"
                                            :style="{'background': `#${query['color']}`}">
```

2023-05-05 09:20 UTC, merged