Webumenia 1903 lottie animation
SlovakNationalGallery/webumenia.sk pull request #838
Opened 2023-04-23 14:32 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

https://user-images.githubusercontent.com/28804184/233845817-2275b8bc-e68b-4191-97c0-768baf168c77.mov

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2023-05-04 05:15 UTC, eronisko requested changes
Please let's use a first-party library instead (since we have the option)

2023-05-04 05:15 UTC, eronisko commented on package.json
> +        "lottie-web-vue": "^2.0.6",
I'd rather use a first-party library (https://github.com/LottieFiles/lottie-player) which exports a web component.

2023-05-04 05:15 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +            <div class="tw-relative tw-min-h-[calc(100vh-14rem)]">
This is strange, but I think I saw it in a different PR as well. Let's see what we can do about it.

2023-05-04 05:15 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                        <empty-artworks-animation></empty-artworks-animation>
I'd extract this out of the component and just use the `<lottie-player>` component directly, passing a URL instead of an object
```suggestion
                        <lottie-player src={{ asset('animations/empty.json') }}></lottie-player>
```

That way the animation doesn't have to become part of the JS bundle (and it's less code)

See https://docs.lottiefiles.com/lottie-player/components/lottie-player/usage#with-reactjs-and-vuejs

2023-05-04 14:43 UTC, FrantisekMichalSebestyen commented
Will wait for #827, then add random search functionality

2023-05-11 05:34 UTC, eronisko approved these changes
LGTM!

All those formatting changes -- is that Prettier starting to work again or not working? :)

2023-05-11 05:34 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                    </lottie-player>
👌

2023-05-11 05:49 UTC, FrantisekMichalSebestyen commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                    </lottie-player>
I made some mistakes while rebasing last PR :( fixed here

2023-05-11 05:49 UTC, merged