Webumenia 1925 extract svg
SlovakNationalGallery/webumenia.sk pull request #857
Opened 2023-05-12 14:08 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2023-05-18 06:55 UTC, eronisko requested changes
I get why you used slots, but I don't think they're the right approach here. Let's see what our options are

2023-05-18 06:55 UTC, eronisko commented on resources/views/components/filter/disclosure_button.blade.php
> +    </x-icons.caret-down>
```suggestion
    <x-icons.caret-down class="tw-ml-2 tw-h-4 tw-w-4 tw-fill-current" />
```

2023-05-18 06:55 UTC, eronisko commented on resources/js/components/catalog-new/PopoverFilter.vue
> +                        <slot v-else name="closed-icon"> </slot>
This isn't making sense to me. The slot is not the right approach here IMHO.

2023-05-18 06:55 UTC, eronisko commented on resources/js/components/catalog-new/ShowMore.vue
> +                <slot v-else name="less-icon"> </slot>
Again, a slot is not appropriate here. Probably best to extract into blade + "show more controller"

2023-05-25 05:56 UTC, eronisko requested changes
This looks really good. 

Please add namespaces to some of the Vue components and take a look at the Prettier mishaps.

2023-05-25 05:56 UTC, eronisko commented on resources/views/components/filter/disclosure_view.blade.php
> +                </x-icons.x>
```suggestion
                <x-icons.x class="tw-h-6 tw-w-6 tw-fill-current" />
```

2023-05-25 05:56 UTC, eronisko commented on resources/views/components/filter/options.blade.php
> +<x-filter.reset_button class="tw-hidden md:tw-flex tw-gap-1 tw-mb-6 tw-mt-5" @click="{{ $attributes->get('v-on:reset') }}">
The `tw-gap-1` class probably belongs inside the component
```suggestion
<x-filter.reset_button class="tw-hidden md:tw-flex tw-mb-6 tw-mt-5" @click="{{ $attributes->get('v-on:reset') }}">
```

2023-05-25 05:56 UTC, eronisko commented on resources/views/components/filter/popover.blade.php
> +                            </x-icons.caret-down>
```suggestion
                            <x-icons.caret-up v-if="pc.isOpen" class="tw-h-4 tw-w-4 tw-fill-sky-300" />
                            <x-icons.caret-down v-else class="tw-h-4 tw-w-4 tw-fill-current" />
```

2023-05-25 05:56 UTC, eronisko commented on resources/views/components/filter/popover.blade.php
> +                <clickaway-wrapper v-if="pc.isOpen" :on-clickaway="pc . closeOpenedPopover">
Something wrong here with spaces

2023-05-25 05:56 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                                                :on-clickaway="sc . toggleIsOpen">
weird space again

2023-05-25 05:56 UTC, eronisko commented on resources/js/app.js
> +Vue.component('clickaway-wrapper', require('./components/catalog-new/ClickawayWrapper.vue').default);
Please distinguish here between reusable and specific components.

Something like the `toggle-controller` is pretty universal, so its name works pretty well. (Maybe I'd consider moving it outside of the `catalog-new` directory, but that can always be done later)

On the other hand, the `search-controller` serves to a specific filter type (multiselect/options). So I'd name it something like `filter.search-controller` or even `filter.options.search-controller`

2023-05-25 05:56 UTC, eronisko commented on resources/views/components/filter/options.blade.php
> +<x-filter.reset_button class="tw-hidden md:tw-flex tw-gap-1 tw-mb-6 tw-mt-5" @click="{{ $attributes->get('v-on:reset') }}">
Also, you're overriding `tw-flex` from inside the component with `tw-hide`. I know it works, but to me it is a bit flaky, because it probably depends on the order of the classes as they are applied. I'd consider using a wrapper and applying the hiding classes on that.

2023-05-25 07:52 UTC, FrantisekMichalSebestyen commented on resources/views/components/filter/popover.blade.php
> +                <clickaway-wrapper v-if="pc.isOpen" :on-clickaway="pc . closeOpenedPopover">
i think prettier is confused with vue **:** short notation and prefers **v-bind** not sure why it works on _index-new_ tho.

2023-05-26 06:20 UTC, eronisko requested changes

2023-05-26 06:20 UTC, eronisko commented on resources/js/components/ToggleController.vue
> +            isOpen: false,
```suggestion
            isOn: false,
```

If we're making a truly generic 'toggle' component I'd expect it to go from _on_ to _off_ rather than _open/closed_. So I'd suggest renaming the state variable.

2023-05-26 06:20 UTC, eronisko commented on resources/js/components/catalog-new/SearchController.vue
Please let's rename this to OptionsSearchController, <filter.options.search-controller>

2023-05-26 06:20 UTC, eronisko commented on resources/js/components/catalog-new/SortController.vue
We're probably missing out on a composition opportunity here. This controller is dealing mostly with the 'popping' aspect and has nothing to do with sorting, really.

To me this seems like a combination of <popover> (Vue) that opens up a select-like menu (Blade with classes based on state from Vue).

2023-05-26 06:21 UTC, eronisko commented on resources/js/components/PopperController.vue
Please include this inside the Popover component

2023-05-26 11:14 UTC, eronisko approved these changes
It's A+

2023-05-26 11:14 UTC, eronisko approved these changes
It's A+

2023-05-26 11:15 UTC, merged