feat: hide filters on empty aggregation results
SlovakNationalGallery/webumenia.sk pull request #861
Opened 2023-05-17 13:29 UTC by FrantisekMichalSebestyen

# Description
Desktop:
https://github.com/SlovakNationalGallery/webumenia.sk/assets/28804184/f75f652d-0446-482e-86af-c9e84d1e132b
Mobile:
https://github.com/SlovakNationalGallery/webumenia.sk/assets/28804184/a112d83a-f151-4fa2-8064-6a346450979a

2023-05-25 06:19 UTC, eronisko requested changes
Hm, this is probably too repetitive even to my liking... You know I'm not a DRY freak, but here we're repeating the same logic over and over again. Let's think about this one some more.

2023-05-26 06:27 UTC, eronisko requested changes
Looks like there are lot of unrelated changes here, please check

2023-05-26 06:27 UTC, eronisko commented on resources/js/components/catalog-new/NewColorSlider.vue
>              :height="12"
These changes probably don't belong here, please double check your commit history

2023-05-26 06:27 UTC, eronisko commented on resources/js/components/catalog-new/NewCustomSelectPopoverLabel.vue
> +    <span class="tw-font-semibold tw-text-base tw-flex tw-gap-1">
```suggestion
    <span class="tw-font-semibold tw-flex tw-gap-1">
```

2023-05-26 06:27 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +        },
Should be under `computed`.

Also the name doesn't seem to fit what it does. How about `filterHasOptions` ?

2023-05-31 11:13 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +        },
Computed does not accept parameters:
I can return function: filterHasOptions{return (param) => ...}
However then there are no benefits to caching and we should use methods
More importanly: **Do not use computed properties to mutate DOM**
So in worst case we can break reactivity in vue
<img width="701" alt="Snímka obrazovky 2023-05-31 o 13 03 42" src="https://github.com/SlovakNationalGallery/webumenia.sk/assets/28804184/3ec39b29-ab01-4750-b0a6-a0588fb15701">
Src: https://vuejs.org/guide/essentials/computed.html#writable-computed

2023-06-01 05:38 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +        },
You're right, I forgot that `computed` didn't accept params. (The other aspects are not a concern -- we're not producing any side effects)

2023-06-01 05:42 UTC, eronisko requested changes
Looking much better, thanks. Please check for redundant `v-if` on the modified components

2023-06-01 05:42 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                        v-if="(hasFilterOptions('topic') && tc.isOpen)" v-if="tc.isOn"
`v-if` is here (and in other places) twice -- please check

2023-06-01 05:50 UTC, FrantisekMichalSebestyen commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                        v-if="(hasFilterOptions('topic') && tc.isOpen)" v-if="tc.isOn"
uff ur right 🤦

2023-06-01 08:18 UTC, eronisko approved these changes
Nice, thanks

2023-06-01 08:18 UTC, eronisko approved these changes
Nice, thanks

2023-06-01 08:18 UTC, eronisko approved these changes
Nice, thanks

2023-06-01 10:41 UTC, merged