error message + no option found dep. on search field
SlovakNationalGallery/webumenia.sk pull request #865
Opened 2023-05-31 13:16 UTC by FrantisekMichalSebestyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (link to Jira or GitHub issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

2023-06-01 05:51 UTC, eronisko requested changes
It looks good, just please fix the error handling so that we don't lose the error completely

2023-06-01 05:51 UTC, eronisko commented on resources/views/frontend/catalog-new/index-new.blade.php
> +                                </reload-controller>
This is fine and consistent, but it could've just been a simple `<reload-button />` component. There is nothing to "control" here
```suggestion
                                <reload-button class="tw-inline-block tw-underline">
                                  obnoviť stránku.
                                </reload-button>
```

2023-06-01 05:51 UTC, eronisko commented on resources/views/components/filter/search_options.blade.php
> +                    src="{{ asset('animations/empty.json') }}">
Didn't we show this animation somewhere else already?

2023-06-01 05:51 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +                this.hasError = true
It would be good to at least log the error into console. Would this work?
```
this.hasError = true
throw e
```

2023-06-01 05:57 UTC, FrantisekMichalSebestyen commented on resources/views/components/filter/search_options.blade.php
> +                    src="{{ asset('animations/empty.json') }}">
yup, should I extract it?

2023-06-08 09:39 UTC, eronisko commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +                this.hasError = true
Can this actually ever recover from `hasError: true`?

2023-06-08 13:22 UTC, FrantisekMichalSebestyen commented on resources/js/components/catalog-new/ItemsFilterController.vue
> +                this.hasError = true
Not really, should it?

2023-06-08 13:52 UTC, eronisko approved these changes

2023-06-08 14:47 UTC, merged