Fix add zoom to api
SlovakNationalGallery/webumenia.sk pull request #878
Opened 2023-07-20 12:36 UTC by FrantisekMichalSebestyen

2023-07-20 16:34 UTC, eronisko requested changes
Thanks for this 👍

2023-07-20 16:34 UTC, eronisko commented on tests/Feature/Api/V2/ItemsTest.php
> +                'images_zoom' => [$image_zoom],
Could you please put the expected result here instead of computing it? (When code under test is duplicated in the test, we get into a weird tautology situation)

2023-07-20 16:34 UTC, eronisko commented on app/Http/Resources/Api/V2/ItemResource.php
> +        $this->loadMissing('images');
I see why this makes sense but this kind of code usually belongs in the controller. (The controller is responsible for querying/data fetching)

2023-07-20 16:34 UTC, eronisko commented on app/Http/Resources/Api/V2/ItemResource.php
> +            }),
We'll likely have more than 'deepZoomUrl' for images. Could we do something like this instead?

```json
"images": [
  {
    "deep_zoom_url": "http://...."
  }
]
```

2023-07-20 18:17 UTC, FrantisekMichalSebestyen commented on tests/Feature/Api/V2/ItemsTest.php
> +                'images_zoom' => [$image_zoom],
Hmm.... not really if I understand correctly. 
You want the test to be independent of .env values. So we need to load them and parse the url.

2023-07-21 06:57 UTC, eronisko approved these changes

2023-07-21 07:00 UTC, merged