Artist role (autor) - parse from artist name and store in separately
SlovakNationalGallery/webumenia.sk pull request #898
Opened 2023-09-17 19:37 UTC by rastislav-chynoransky

https://jira.sng.sk/browse/WEBUMENIA-1533

2023-09-21 12:32 UTC, eronisko requested changes
I'm sure this code works but I'm having a hard time understanding it. Could you please take a look at the suggestions and/or could we have chat about this?

2023-09-21 12:32 UTC, eronisko commented on app/Item.php
> +    }
Just to make sure I understand: this removes all automatically_matched authorities that are not present in `$idsWithPivotData` keys?

Would this work too?

```suggestion
    {
        $this->authorities()->wherePivot('automatically_matched', true)->sync(
            $idsWithPivotData->map(
                fn($pivotData) => [
                    'automatically_matched' => true,
                    ...$pivotData,
                ]
            )
        );
    }
```

If so, could it be inlined instead? (I can only see it used once)

2023-09-21 12:32 UTC, eronisko commented on tests/Models/ItemTest.php
> +    public function testSyncMatchedAuthorities()
I'm very happy to see a test here but I'm having trouble understanding what it does :(

Could you perhaps work it into a more higher-level test case for `GmuhkItemImporter`?

Maybe a test like this

```php
public function testParseRoleFromArtistName() 
{
    $data = [...];
    GmuhkItemImporter::import($data);
    $this->assertEquals('expected role', Item::first()->authorities[0]->role)
}
```

2023-09-21 12:50 UTC, rastislav-chynoransky commented on app/Item.php
> +    }
This approach won't work because the `wherePivot` condition will limit the scope of pivot records, effectively leading to inserts of duplicate pivots if there already exist some with `automatically_matched = false`

2023-09-21 13:04 UTC, rastislav-chynoransky commented on app/Item.php
> +    }
And for now this change is made only for GMUHK gallery, however it will get reused in CSV importers (or any new data source).

2023-09-21 13:23 UTC, rastislav-chynoransky commented on tests/Models/ItemTest.php
> +    public function testSyncMatchedAuthorities()
In fact the test makes multiple assertions and could be split into five scenarios:
- _automatically_ matched that are _present_ in newly matched are expected _to stay_ there (with updated pivot data)
- _manually_ matched that are _present_ in newly matched are expected _to stay_ there (with updated pivot data)
- _automatically_ matched that are _missing_ from newly matched are expected _to be deleted_
- _manually_ matched that are _missing_ from newly matched are expected _to stay_ there
- and finally any new matches should be created

Of course I can create a higher-level test for importing role, but the test of these relationship changes should stay on the model-level.

2023-09-21 21:47 UTC, rastislav-chynoransky commented on tests/Models/ItemTest.php
> +    public function testSyncMatchedAuthorities()
added higher-level test https://github.com/SlovakNationalGallery/webumenia.sk/pull/898/commits/892ca5bd099db0a85634f5734ed6dc6cfecad0f0

2023-09-22 11:44 UTC, rastislav-chynoransky commented on app/Item.php
> +    }
@eronisko I've included your suggestion discussed via slack https://github.com/SlovakNationalGallery/webumenia.sk/pull/898/commits/84c5076013700a810f02b97e0f4d49f4fe73d474

2023-09-22 12:23 UTC, eronisko approved these changes
I've got a couple more suggestions with the global `withPivot` being a serious concern. Otherwise, this is good to go, thank you.

2023-09-22 12:23 UTC, eronisko commented on tests/Harvest/Importers/GmuhkItemImporterTest.php
> +        $this->assertEquals('fotograf', $item->authorities[0]->pivot->role);
Very nice, thank you

2023-09-22 12:27 UTC, merged